### PR TITLE
Display and store version of the flashed file

### PR DESCRIPTION
**Pull request by wiklam**

### CODE REVIEW

**Comment by ibexq** [comment]
Was it really meant that the "file version" should overwrite the systemname?

**Comment by ibexq** [comment]
What is the file content in the file section of the GUI? Is is a hash sum? If so i would rename it to a hashsum instead of content.

**Comment by ibexq** [comment]
Would be nice if the file size is in MB. Not a must but at least B or Bytes instead of no unit would be good.

**Comment by wiklam** [comment]
> Was it really meant that the "file version" should overwrite the systemname?
> 
> It is also not overwriting the whole name just as many characters as the new name has.

It was previously called software version, later on we changed it system name.

> What is the file content in the file section of the GUI? Is is a hash sum? If so i would rename it to a hashsum instead of content.

It is the first n (20?) bytes of the file

> Would be nice if the file size is in MB. Not a must but at least B or Bytes instead of no unit would be good.
It is not in the scope of the task but it is missing the B, I am adding it.

**Comment by ibexq** [comment]
> It was previously called software version, later on we changed it system name.

Then i think it's confusing that the gui calls it system name on the left in the table and file version on the right next to the choose file button.

**Review by ibexq — APPROVED** [review]

**Pull request merged**
